<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-08-17T09:50:11" tests="0" file="cypress/integration/second.test.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="My First Test" timestamp="2021-08-17T09:50:11" tests="1" time="0.0000" failures="1">
    <testcase name="My First Test clicking type navigates to a new url" time="0.0000" classname="clicking type navigates to a new url">
      <failure message="Timed out retrying after 4000ms: expected &apos;https://example.cypress.io/commands/actions&apos; to include &apos;/commannds/actions&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected 'https://example.cypress.io/commands/actions' to include '/commannds/actions'
    at Context.eval (https://example.cypress.io/__cypress/tests?p=cypress/integration/second.test.ts:101:18)]]></failure>
    </testcase>
  </testsuite>
</testsuites>